import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guidesSidebar: [{ type: "autogenerated", dirName: "guides" }],
  packagesSidebar: [{ type: "autogenerated", dirName: "packages" }],
  testsSidebar: [{ type: "autogenerated", dirName: "tests" }],
  ruTestsSidebar: [{ type: "autogenerated", dirName: "ru-tests" }],
  enPostsSidebar: [{ type: "autogenerated", dirName: "en-posts" }],
  ruPostsSidebar: [{ type: "autogenerated", dirName: "ru-posts" }],
  ruGuidesSidebar: [{ type: "autogenerated", dirName: "ru-guides" }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
